spring:
  application:
    name: api-service
  config:
    import: "optional:configserver:"
  cloud:
    consul:
      host: consul-server
      port: 8500
  zipkin:
    base-url: http://jaeger:9411

server:
  port: 8301
management:
  server:
    port: 9301
  endpoints:
    web:
      exposure:
        include: health,traces
  endpoint.traces.capacity: 2

appkey:
  url: http://gateway-server:8000/appkey-service/sm01/