spring:
  application:
    name: api-service
  config:
    import: "optional:configserver:"
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      discovery:
        enabled: true
        service-id: cloud-config-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/db_tables?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: 4321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

server:
  port: 8100
management:
  server:
    port: 9100
  endpoints:
    web:
      exposure:
        include: health,traces
  endpoint.traces.capacity: 3

appkey:
  url: http://appkey-service/sm01/

logging:
  file:
    path: /opt/api-server/

---

spring:
  config:
    activate:
      on-profile: dev1
  cloud:
    consul:
      enabled: true

server:
  port: 8300
management:
  server:
    port: 9300

logging:
  file:
    path: /logs/api-server-1/

---

spring:
  config:
    activate:
      on-profile: dev2
  cloud:
    consul:
      enabled: true

server:
  port: 8301
management:
  server:
    port: 9301

logging:
  file:
    path: /logs/api-server-2/

---

spring:
  config:
    activate:
      on-profile: docker1
  zipkin:
    base-url: http://jaeger:9411
  datasource:
    url: jdbc:mysql://db-mysql:3306/db_tables?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true

server:
  port: 8300
management:
  server:
    port: 9300

logging:
  file:
    path: /logs/api-server-1/

---

spring:
  config:
    activate:
      on-profile: docker2
  zipkin:
    base-url: http://jaeger:9411
  datasource:
    url: jdbc:mysql://db-mysql:3306/db_tables?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true

server:
  port: 8301
management:
  server:
    port: 9301

logging:
  file:
    path: /logs/api-server-2/

