spring:
  application:
    name: api-service
  config:
    import: "optional:configserver:"
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      discovery:
        enabled: true
        service-id: cloud-config-server
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8300
management:
  server:
    port: 9300
  endpoints:
    web:
      exposure:
        include: health,traces
  endpoint.traces.capacity: 3

appkey:
  url: http://localhost:8100/sm01/