spring:
  application:
    name: appkey-service
  config:
    import: "optional:configserver:"
  data:
    cassandra:
      contact-points: 192.168.35.204
      port: 9042
      keyspace-name: keys
      local-datacenter: dc1
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      discovery:
        enabled: true
        service-id: cloud-config-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8100
management:
  server:
    port: 9100
  endpoints:
    web:
      exposure:
        include: health,traces
  endpoint.traces.capacity: 3

logging:
  file:
    path: /opt/appkey-server/

---

spring:
  config:
    activate:
      on-profile: dev1
  cloud:
    consul:
      enabled: true

server:
  port: 8100
management:
  server:
    port: 9100

logging:
  file:
    path: /logs/appkey-server-1/

---

spring:
  config:
    activate:
      on-profile: dev2
  cloud:
    consul:
      enabled: true

server:
  port: 8101
management:
  server:
    port: 9101

logging:
  file:
    path: /logs/appkey-server-2/

---

spring:
  config:
    activate:
      on-profile: docker1
  zipkin:
    base-url: http://jaeger:9411

server:
  port: 8100
management:
  server:
    port: 9100

logging:
  file:
    path: /logs/appkey-server-1/

---

spring:
  config:
    activate:
      on-profile: docker2
  zipkin:
    base-url: http://jaeger:9411

server:
  port: 8101
management:
  server:
    port: 9101

logging:
  file:
    path: /logs/appkey-server-2/

