spring:
  application:
    name: appkey-service
  config:
    import: "optional:configserver:"
  cloud:
    consul:
      host: localhost
      port: 8500
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8101
management:
  server:
    port: 9101
  endpoints:
    web:
      exposure:
        include: health,traces
  endpoint.traces.capacity: 2