spring:
  application:
    name: appkey-service
  config:
    import: "optional:configserver:"
  data:
    cassandra:
      contact-points: 192.168.35.204
      port: 9042
      keyspace-name: keys
      local-datacenter: dc1
  cloud:
    consul:
      host: consul-server
      port: 8500
  zipkin:
    base-url: http://jaeger:9411

server:
  port: 8101
management:
  server:
    port: 9101
  endpoints:
    web:
      exposure:
        include: health,traces
  endpoint.traces.capacity: 3

active:
  profile:
    name: docker2