spring:
  application:
    name: "cloud-gateway"
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: appkey-service
          uri: lb://appkey-service
          predicates:
            - Path=/appkey/**
          filters:
            - RewritePath=/appkey/?(?<segment>.*), /$\{segment}
        - id: api-service
          uri: lb://api-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    loggers:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    consul:
      host: localhost
      port: 8500
  zipkin:
    base-url: http://localhost:9411

---

spring:
  config:
    activate:
      on-profile: docker
  cloud:
    consul:
      host: consul-server
      port: 8500
  zipkin:
    base-url: http://jaeger:9411

logging:
  file:
    path: /opt/gateway/