spring:
  application:
    name: cloud-config-server
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      server:
        git:
          uri: https://github.com/choiis/config-yml
server:
  port: 8200
management:
  server:
    port: 9200
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    loggers:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true

logging:
  file:
    path: /opt/config/

---
spring:
  config:
    activate:
      on-profile: dev1
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true

server:
  port: 8200
management:
  server:
    port: 9200

ogging:
  file:
    path: /logs/config/

---
spring:
  config:
    activate:
      on-profile: dev2
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true

server:
  port: 8201
management:
  server:
    port: 8201

ogging:
  file:
    path: /logs/config/

---
spring:
  config:
    activate:
      on-profile: docker1
  cloud:
    consul:
      host: consul-server
      port: 8500
      enabled: true

server:
  port: 8200
management:
  server:
    port: 9200

ogging:
  file:
    path: /logs/config/

---
spring:
  config:
    activate:
      on-profile: docker2
  cloud:
    consul:
      host: consul-server
      port: 8500
      enabled: true

server:
  port: 8201
management:
  server:
    port: 8201

ogging:
  file:
    path: /logs/config/
